// src/app/layout.tsx (or wherever your RootLayout is defined)
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css"; // Ensure the path is correct
import { Provider } from "react-redux";
import { store } from "../store/store"; // Adjust the path if necessary
import ClientRootLayout from "./ClientRootLayout";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
import LinknavigationBanner from "../components/LinknavigationBanner"
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "medi-mall",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientRootLayout>
          <Header/>
          <Navbar />
          <LinknavigationBanner/>
          {children}
          <Footer/>
        </ClientRootLayout>
      </body>
    </html>
  );
}
